export const GENERATE = 'GENERATE'
export const DRAW = 'DRAW'
export const TOGGLE_DRAW_THREE = 'TOGGLE_DRAW_THREE'
export const UNDO = 'UNDO'
export const SHARE = 'SHARE'
export const TOAST = 'TOAST'

export const TIMER_START = 'TIMER_START'
export const TIMER_STOP = 'TIMER_STOP'
export const TIMER_RESET = 'TIMER_RESET'
export const TIMER_TICK = 'TIMER_TICK'
export const TIMER_RESTART = 'TIMER_RESTART'

export const CUSTOMIZE_SUIT = 'CUSTOMIZE_SUIT'
export const CUSTOMIZE_SUIT_END = 'CUSTOMIZE_SUIT_END'
export const CHANGE_SUIT_EXERCISE = 'CHANGE_SUIT_EXERCISE'
